---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  print-debug-info:
    name: Print debug info
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3

  check-mergeability:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: networkservicemesh/.github/.github/workflows/check-mergeability.yaml@main
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  automerge:
    needs: [check-mergeability]
    if: ${{ needs.check-mergeability.outputs.pr_branch_ref != && startsWith(github.event.workflow_run.head_commit.message, '[github-actions]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Automerge
        run: gh pr merge ${{ github.event.workflow_run.head_branch }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
