---
name: Print Commit Author

on:
  push:
    branches:
      - main

jobs:
  print_author:
    runs-on: ubuntu-latest
    steps:
      - name: Print commit author
        id: print_author
        run: echo "${{ github.event.commits[0].author.name }}"

