name: Print Commit Author

on:
  push:
    branches:
      - main

jobs:
  print_author:
    runs-on: ubuntu-latest
    if: ${{ github.event.commits[0].author.name == 'bszirtes' }}
    steps:
      - name: Print commit author
        id: print_author
        run: echo "The author was bszirtes"

