---
name: Update dependent repositories
on:
  push:
    branches:
      - main
jobs:
  update-dependent-repositories:
    strategy:
      matrix:
        repository:
          - integration-tests
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.commits[0].message, '[github-actions]') }}
    steps:
      - name: Update dependent repositories
        run: |
          echo "UPDATING STARTED"
